name = "scribe"
version = "1.0.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
envoy = "~> 1.0"
logging = "~> 1.0"
glyph = { path = "../glyph" }
gleam_erlang = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 1.0"
